### ISSUE TITLE
SNOW-1689013: Unable to open a snowflake connection from services deployed in Linux containers

### ISSUE THREAD

**Issue by gowtham-chittoor-sp** [snowflakedb/snowflake-connector-net#1030]
### Issue description
We are facing issue while opening a session from services deployed in Linux containers

### Error log
A task was canceled at Snowflake.Data.Core.SFSession.Open()    at Snowflake.Data.Client.SnowflakeDbConnection.Open()  
There is an example in READMD.md file showing you how to enable logging.

*Dotnet framework and version: .Net 8
Driver version - 1.0.9

Additional Info
- Its working from Snowflake CLI
- We see this problem from services (Linux based only) deployed in US region accessing snowflake US but EU geo location works fine.
- We have services deployed in windows and dont see any issue there.

**Comment by sfc-gh-dszmolka** [comment]
hello - if the driver version is _really_ 1.0.9, that is very very old and you'll need to upgrade [to a supported version](https://docs.snowflake.com/en/release-notes/requirements#recommended-client-versions) or preferably, the latest.

otherwise, do you think it would be possible to share any evidence of the issue, like error message, logs, anything which could help troubleshooting ? 
to rule out basic connectivity issues, you could also take a look at [SnowCD](https://docs.snowflake.com/en/user-guide/snowcd) and validate that all Snowflake endpoints are reachable from the given source.

Finally; if you prefer not to share any logs or other data here where they are publicly visible - that is entirely fine. In this case, please [raise a Support Case with us](https://community.snowflake.com/s/article/How-To-Submit-a-Support-Case-in-Snowflake-Lodge) and you can work with a support engineer 1:1.

**Comment by sfc-gh-dszmolka** [comment]
closing this issue as there's been no response for a while now; comment please if further help is needed and can reopen.
