### ISSUE TITLE
SNOW-360853: v 1.2.3 all .Open() calls timeout after some 503s observed

### ISSUE THREAD

**Issue by shawnjones253** [snowflakedb/snowflake-connector-net#324]
### Issue description
Using v1.2.3 of the connector, I'm seeing the following issue:

1. An HTTP 503 is returned from snowflake after calling ExecuteDbDataReader: `LogLevel: DEBUG
LogMessage: Failed Response: StatusCode: 503, ReasonPhrase: 'Service Temporarily Unavailable'`
2. A few requests after this will succeed normally.
3. Suddenly, all requests get stuck in timeouts when calling `SnowflakeDbConnection.Open()`:
- `LogLevel: DEBUG, LogMessage: Open Session`
- `LogLevel: WARN, LogMessage: Http request timeout. Retry the request`
- `LogLevel: DEBUG, LogMessage: Sleep 1 seconds and then retry the request`
- `LogLevel: WARN, LogMessage: Http request timeout. Retry the request`
- `LogLevel: DEBUG, LogMessage: Sleep 2 seconds and then retry the request`
- ...
- `LogLevel: WARN, LogMessage: Http request timeout. Retry the request`
- `LogLevel: DEBUG, LogMessage: Sleep 16 seconds and then retry the request`

Unfortunately, I don't have a good way to reproduce this issue, but I can share private logs if it helps. This issue is new after upgrading from v 1.2.0 to v 1.2.3.

### Example code
Note: each "request" uses its own instance of `SnowflakeDbConnection`. That is, we are using something like:

```cs
using (var connection = new SnowflakeDbConnection())
{
    connection.ConnectionString = ...;
    connection.Open()
    connection.CommandText = "select * from ...";
}
```

### Configuration
*Driver version: v1.2.3*

*Dotnet framework and version:* .net framework 4.7.0

*Server version: 5.19.2*

*Client OS: Multiple versions of Windows Server, including 2012 r2 and 2016*

**Comment by zzzv1r** [comment]
I guess that this issue and  https://github.com/snowflakedb/snowflake-connector-net/issues/301 are the same. And that is because of HttpTimeout setting is hardcoded to 16 seconds here 
![image](https://user-images.githubusercontent.com/86001319/122226691-e2da5680-cebe-11eb-8518-a8421e26588a.png).
Also, there is no possibility to override it rather than RestTimeout which can be overridden by parameter CONNECTION_TIMEOUT in connection string.
Our snowflake is not so fast as we want it so sometimes login via library take 10-11 seconds but that still enough to perform session, but on kubernetes cluster it fails all the time as session time outed and there is no possibility to set more that 15 seconds. But when I set for example 1 min (compiled library from sources by myself) that all works, a little slow but anyway it works.
So maybe there is possibility to add parameter similar to CONNECTION_TIMEOUT but for httpTimeout and not for restTimeout?

**Comment by OxQ** [comment]
We have the same issues, any updates on this?

**Comment by bbondarets** [comment]
My team faces this issue as well. We would be really grateful if you could fix this.
Looking forward for any updates.

**Comment by alexrosenfeld10** [comment]
FWIW, I see this in my private fork with the latest code changes from master in this repo. It's pretty devastating, and I'm holding off on releasing a bunch of the other important changes from upstream (this repo) to my private fork because of it.

**Comment by sfc-gh-jtang** [comment]
To clean up and re-prioritize more pressing bugs and feature requests we are closing all issues older than 6 months as of April 1, 2023. If there are any issues or feature requests that you would like us to address, please create them according to the new templates we have created. For urgent issues, opening a support case with this link Snowflake Community is the fastest way to get a response.
