### ISSUE TITLE
SNOW-364370: Error with Snowflake .NET Driver for Azure Function for Key-Value pair authentication

### ISSUE THREAD

**Issue by leopinheirohk** [snowflakedb/snowflake-connector-net#330]
I have implemented the solution described here for connecting ADF to Snowflake: https://www.snowflake.com/blog/snowflake-connector-for-azure-data-factory-adf/

This solution uses Azure Function and the Snowflake .Net Driver (https://docs.snowflake.com/en/user-guide/dotnet-driver.html)

I have been successful until now by connecting to Snowflake by user and password. For example: `account=testaccount;user=testuser;password=XXXXX;db=testdb;schema=testschema`

However due to security concerns I need to change this connection type to Key-Value pair:
`account=testaccount;authenticator=snowflake_jwt;user=testuser;private_key_file={pathToThePrivateKeyFile};private_key_pwd={passwordForDecryptingThePrivateKey};db=testdb;schema=testschema`

However when attempting to do so I get the following error when opening the connection with Snowflake:

```
System.IO.FileNotFoundException: Could not load file or assembly 'System.IdentityModel.Tokens.Jwt, Version=6.10.2.0, Culture=neutral, PublicKeyToken=31bf3856ad364e35'. The system cannot find the file specified.
File name: 'System.IdentityModel.Tokens.Jwt, Version=6.10.2.0, Culture=neutral, PublicKeyToken=31bf3856ad364e35'
   at Snowflake.Data.Core.Authenticator.KeyPairAuthenticator.GenerateJwtToken()
   at Snowflake.Data.Core.Authenticator.KeyPairAuthenticator.Authenticate()
   at Snowflake.Data.Core.SFSession.Open()
   at Snowflake.Data.Client.SnowflakeDbConnection.Open()
```

I also tried to create a simple Console App (.Net Framework 4.7.2) and this issue **does not** happen. Therefore it seems to occur only with Azure Functions (.Net Core 3.1).

Any thoughts on this?

**Comment by GregoryHorvath** [comment]
We have this same issue (even with the Python version of the connector).

We had the private key in an Azure Storage and tried to use the URL but after logging the path the connector uses, it seemed that by default it uses the project's root path or something like that, and only appends the given path to that.
We also tried to use the private key as an Azure Key Vault secret and use the `PRIVATE_KEY` parameter instead of the `PRIVATE_KEY_FILE`, using either a single-line formatted private key or the multi-line version, but no success.

I'm still not sure if this is an issue how Azure handles the secrets or an issue with the Snowflake connectors (I'm somewhat of a beginner with Azure).

**Comment by ryan-kramer-ab** [comment]
@GregoryHorvath if you are using the ConnectionStringBuilder, then PRIVATE_KEY might not work due to https://github.com/snowflakedb/snowflake-connector-net/issues/370

**Comment by GregoryHorvath** [comment]
@ryan-kramer-ab Thanks for the tip, but sadly that's not the issue for us because we just construct the connectionstring manually. Also from a local run the connection works, and I've (re)checked all the secrets in Azure multiple times and they're exactly the same strings as in our local environment. So no clue so far.

**Comment by pserafin** [comment]
I can only confirm above. The issue occurs when Azure Function is trying to authenticate. The issue does not occur when function is hosted locally. As a test we've switched to PRIVATE_FILE_KEY and published file with token during deployment - which fixed authorisation issue.
Mentioned [370](https://github.com/snowflakedb/snowflake-connector-net/issues/370) seems to be source of that issue

**Comment by sfc-gh-dszmolka** [comment]
hello and thank you for submitting this issue, also apologies for the long period without response. to confirm this is still an issue with the recent drivers, could someone who experiences it:
* upgrade to the latest version of the driver (today `2.0.24`)
* test if it still happens
* if it does, post a minimal viable code snippet which when run, reproduces the issue. also since this seems to be environment specific, please post any details which you think is important about the environment.

i'll reopen the issue and continue troubleshooting. thank you in advance !
