### ISSUE TITLE
SFSession Auth Token Expirations

### ISSUE THREAD

**Issue by akrock** [snowflakedb/snowflake-connector-net#37]
We have hit some cases where during long 4 hour+ processing the tokens will no longer renew, and we receive the following exception.

```
Snowflake.Data.Client.SnowflakeDbException: Authentication token has expired.  The user must authenticate again.
   at Snowflake.Data.Core.SFSession.renewSession() in C:\Projects\obelisk\NuGets\thirdpartylibs\snowflake-connector-net\snowflake-connector-net\Snowflake.Data\Core\SFSession.cs:line 229
   at Snowflake.Data.Core.SFStatement.<ExecuteAsync>d__25.MoveNext() in C:\Projects\obelisk\NuGets\thirdpartylibs\snowflake-connector-net\snowflake-connector-net\Snowflake.Data\Core\SFStatement.cs:line 171
---> (Inner Exception #0) Error: Authentication token has expired.  The user must authenticate again. SqlState: , VendorCode: 390114, QueryId: <---
```

How can this be resolved? I assume that if we login again after the failure in renewSession we would be unable to access any temp tables or other session level stuff that existed on the previous session.

**Comment by howryu** [comment]
This is the expected behavior. Non-active session for more than 4 hours will be expired. This is mainly for security concern. There is a parameter https://docs.snowflake.net/manuals/sql-reference/parameters.html#client-session-keep-alive, which is honored by JDBC and ODBC. Internal implementation is just having a background thread heartbeating to the server every hour to avoid master token expiration. (There is a renewSession method in SFSession.cs, which use master token to renew session token, which is expired every hour). In your case, master token is expired.

**Comment by howryu** [comment]
@akrock I opened a separate issue to track implementation of heartbeat in .net driver. No ETA on this feature. I guess a dummy workaround is issuing a `select 1` every hour in your background.

**Comment by akrock** [comment]
@howryu in this case the connection was not idle it was executing a query for more than 4 hours. Is this still the expected behavior?

**Comment by howryu** [comment]
Hmmm, that does not sounds the expected behavior. Sounds like a bug. I will reopen the issue.

**Comment by howryu** [comment]
@akrock Do you know which version of .NET driver are you using? I think we fix some session renew issue in latest version.

**Comment by howryu** [comment]
No response in one month. Close the ticket for now.
