### ISSUE TITLE
What is TIMEOUT_PER_HTTP_REQUEST and TIMEOUT_PER_REST_REQUEST

### ISSUE THREAD

**Issue by Grauenwolf** [snowflakedb/snowflake-connector-net#463]
When I do a web search for these strings, I don't see them appear anywhere except this repository.

* https://www.google.com/search?q=%22TIMEOUT_PER_HTTP_REQUEST%22
* https://www.google.com/search?q=%22TIMEOUT_PER_REST_REQUEST%22

What do they actually do? Is this a Snowflake thing? I ask because I can't see anywhere where .NET uses them.

**Comment by sfc-gh-dszmolka** [comment]
hi and apologies for the long period without response, hopefully you found the response since posting, but in case anyone stumbles into this in the future:

the first one seems to be a generic [http request timeout](https://github.com/snowflakedb/snowflake-connector-net/blob/v2.0.24/Snowflake.Data/Core/RestRequest.cs#L116) (16s per default) and the second for [the REST request](https://github.com/snowflakedb/snowflake-connector-net/blob/v2.0.24/Snowflake.Data/Core/RestRequest.cs#L31) (120s per default), which we use when constructing http requests.
