### ISSUE TITLE
Fails to connect to Snowflake - .NET

### ISSUE THREAD

**Issue by tandasima** [snowflakedb/snowflake-connector-net#6]
Was this driver tested on dot net? It doesn't seem to successfully connect to Snowflake at all.

**Comment by howryu** [comment]
@tandasima Can you provide me with my detail? Logging? Also what framework are you using? What is the version?

The project is tested on appveyor https://ci.appveyor.com/project/howryu/snowflake-connector-net/branch/master.

**Comment by tandasima** [comment]
The currently underlying error seems to be ```The underlying connection was closed: Could not establish trust relationship for the SSL/TLS secure channel.```

My connection string looks like ```account=companyname.us-east-1;host=snowflakecomputing.com;user=myusername;password=mypassword```

I also tried different variations of the connection string.

Any idea what could be the issue? Looks like others are able to connect.

**Comment by howryu** [comment]
Looks like a certificate issue. Clients failed to establish a TLS connection with server. 

Also, it seems that you are trying to connect to us-east deployment, which use newer certificate and only accept tls 1.2 connection. 

Have you tried upgrade your windows? What is your OS and version? Because .net connector truly depends on windows secure channel to establish tls connection, it is possible that your windows environment is out of date.

I will also have a try on my side to see if I can connect to us-east deployment. Since all my appveyor is running against us-west.

**Comment by howryu** [comment]
Update: I have tried on my laptop to connect to a us-east-1 deployment and did not have an issue.

Two other options you could try:
1) Try connecting to Snowflake UI in InternetExplorer (I guess IE might use Windows Schannel as well) to see if you can connect to Snowflake.
2) Try to get TCP dump to understand in which step of TLS handshake failed.

**Comment by JhonPaul1234** [comment]
Hey @tandasima  did it worked for your project......?

**Comment by howryu** [comment]
@tandasima Did you figure out the issue? If not, can you try latest Snowflake.Data 0.3.0, which support .net core 2.0, which might resolve your issue.

**Comment by tandasima** [comment]
@howryu Thanks for the update. Will try the latest 0.3.0 and update you.

Cheers!

**Comment by andrewabril** [comment]
Has anyone resolved this issue? I am using the NuGet package v0.3.0 and running on LinqPad 5, but still receiving the following error:

> The underlying connection was closed: Could not establish trust relationship for the SSL/TLS secure channel. 

Thanks!

**Comment by howryu** [comment]
@andrewabril This could be because your windows is out of date. Are you in latest windows? We rely on winssl (schannel) to establish tls connection with server. Have you tried enable network logs? Example is here https://github.com/snowflakedb/snowflake-connector-net/blob/master/Snowflake.Data.Tests/App.config

**Comment by howryu** [comment]
Closed since no response.

**Comment by howryu** [comment]
Unfortunately, I have not tested every windows machine. Can you share the network log with me?
