### ISSUE TITLE
Heartbeat may crash the app

### ISSUE THREAD

**Issue by afilatov-st** [snowflakedb/snowflake-connector-net#695]
Please answer these questions before submitting your issue. 
In order to accurately debug the issue this information is required. Thanks!

1. What version of .NET driver are you using?

2.0.20
   
2. What operating system and processor architecture are you using?

Docker image `mcr.microsoft.com/dotnet/sdk:7.0.201-bullseye-slim-amd64`
   
3. What version of .NET framework are you using?
   E.g. .net framework 4.5.2 or .net standard 2.0

7.0.201
   
4. What did you do?

Added `CLIENT_SESSION_KEEP_ALIVE=true` to the connection string

5. What did you expect to see?

Connection is kept alive for long-running queries.

6. Can you set logging to DEBUG and collect the logs?

The following exception crashes the app because the heartbeat is run in a thread without error handling.

```
Unhandled exception. Snowflake.Data.Client.SnowflakeDbException (0x80004005): Error: Session no longer exists. New login required to access the service. SqlState: , VendorCode: 390111, QueryId:
...
at Snowflake.Data.Core.HeartBeatBackground.heartBeatAll()

```

7. What is your Snowflake account identifier, if any? (Optional)

**Comment by sfc-gh-dszmolka** [comment]
hello and thank you for raising this issue. should be fixed with #642 , which is available with driver versions 2.0.23 and up. can you please upgrade the driver and try to see if you're still affected ?

if so, please update this Issue with the details and the DEBUG logs and we'll troubleshoot further. (if you don't want to share debug logs here, please [raise a case with Snowflake Support](https://community.snowflake.com/s/article/How-To-Submit-a-Support-Case-in-Snowflake-Lodge) to work 1:1 with us)
but hopefully this will be unnecessary as the issue should be fixed with a later driver version which is already available for download.
