### ISSUE TITLE
SNOW-927403: Bind variable not set error - passing array to snowflake SQL SP

### ISSUE THREAD

**Issue by cse-manish** [snowflakedb/snowflake-connector-net#780]
"Bind variable not set" error coming when passing array type parameter to snowflake SQL SP. Please see attached screenshot. 

Please answer these questions before submitting your issue. 
In order to accurately debug the issue this information is required. Thanks!

1. What version of .NET driver are you using?
=>4.7.2 dot net framework, using latest version of snowflake connector
   
2. What operating system and processor architecture are you using?
=>Windows
   
3. What version of .NET framework are you using?
   E.g. .net framework 4.5.2 or .net standard 2.0
   => 4.7.2 dot net framework 

4. What did you do?
=> I am trying to call a snowflake SQL SP that takes array input parameter from dot net code. The program is giving "bind variable :p_id not set" error. 
Please see attached screenshot. 
P_id is my array type input param in the SP. 
Sorry for pasting screenshot instead of actual code text, github website is blocked on my office intranet.

5. What did you expect to see?
=> expecting the DB CALL to go successfully instead of seeing an error

6. Can you set logging to DEBUG and collect the logs?

   https://community.snowflake.com/s/article/How-to-generate-log-file-on-Snowflake-connectors
   
   There is an example in READMD.md file showing you how to enable logging.
7. What is your Snowflake account identifier, if any? (Optional)

![1695964615660784548994147735817](https://github.com/snowflakedb/snowflake-connector-net/assets/146411415/a087b02f-45c8-4e7a-b49b-bef2bcc2c829)

**Comment by sfc-gh-dszmolka** [comment]
hi and thank you for submitting this issue! i'm probably missing something, but is there a specific reason you're using `ExecuteScalar` ?
Perhaps it's worth a try using the [example from the documentation](https://github.com/snowflakedb/snowflake-connector-net#bind-array-variables) and
* calling `ExecuteNonQuery` instead of `ExecuteScalar` 
* even though I think a named variable should work (`:P_ID`) but how about trying `?` instead, does it. make a difference ?

**Comment by cse-manish** [comment]
Hello David, thanks for your reply. I am using ExecuteScaler as my SP is
returning one single value. But I am getting the same error regardless of
ExeciteScaler or ExecuteNonQuery.
The example you referred is working for the direct INSERT query, but
somehow not working for the stored procedure. If it's not too much to ask,
any chance you can try this for a test stored procedure and see if it works
for you?
Thanks in advance.

**Comment by sfc-gh-dszmolka** [comment]
tested this and got to the same error as you do. when feeding the arguments to the SP as an array binding, it fails with `Bind variable :P_ID not set.` . 
interestingly, if I feed the same array of input in a 'hardcoded' way (`CALL test_db.public.test([1011,1012]);`) instead of array binding, it works. so at this point I'm not sure if this is an expected behaviour - we're going to take a look and I'll keep this ticket posted with the investigation results.

**Comment by sfc-gh-dszmolka** [comment]
no update on this for a while so marking it as closed - if you still think you hit a bug in the Snowflake .NET driver, please comment with the details and we can look into it further.

**Comment by powerpoint123** [comment]
this is still an issue, can it be addressed?
