### ISSUE TITLE
Add proxy support

### ISSUE THREAD

**Issue by howryu** [snowflakedb/snowflake-connector-net#96]
### Issue description
Currently there is no way to specify proxy in .net driver. This should be supported.

**Comment by plaisted** [comment]
Are there any plans to get this added? This is important for connecting from on premise servers to AWS Private Link connection to Snowflake.

**Comment by arunbalaa** [comment]
is this still in progress ?

I ran a sample .NET application trying to open a snowflakedbconnection, which worked with no issues. Now I carried the same connection string to the production application which is hosted in my organization's server, and it fails. I get an exception "a task was canceled" while trying to open a connection. Do you think this might be because of proxy ?

PS: A different team is using python driver and their connection was successful only after going thru the proxy.

**Comment by xuanzhiyi** [comment]
This is quite critical for large corporate customers. Should this feature be prioritized?

**Comment by malhotrar** [comment]
We would love to consume this library for an upcoming project, but would be unable to do so without this feature? Is there any sort of update on when #261 may be merged?
